---
kind: ConfigMap
metadata:
  name: kube-test-boilerplate
  namespace: default
apiVersion: v1
data:

  setup.sh: |-
    touch /tmp/testlog

    #npm install -g \
    #  request@2.83.0 \
    #  request-promise-native@1.0.5 \
    #  --ignore-scripts >> /tmp/testlog

    mocha --watch --reporter=tap --preserve-symlinks $TESTS >> /tmp/testlog 2>&1 &

    tail -f /tmp/testlog

  run.sh: |-
    exec >> /tmp/testlog
    exec 2>&1

    tail -n 3 /tmp/testlog > /tmp/lastresult
    echo ""
    echo "### Checking latest result, at $(date -u --iso-8601='ns')"
    for F in $(ls $TESTS); do echo "# To update $F run: kubectl cp $F $(hostname):$(pwd)/$F"; done
    # exit non-zero unless result of latest mocha run is positive
    # trigger next run (set periodSeconds in readinessProbe to increase time between checks)
    touch -c $TESTS
    # exit 0 only if no failures
    tail -n 1 /tmp/lastresult | grep "# fail 0" > /dev/null

  quit-on-nonzero-exit.sh: |-
    exec >> /tmp/testlog
    exec 2>&1

    exit 0

  # tests, that you might want to develop using REPL
  test-something.js: |-
    describe("A test", () => {

      it("Runs through mocha", () => {
        console.log('Running', new Date());
      });

    });

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-test-boilerplate
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        test-target: kube-test
        test-type: readiness
    spec:
      containers:
      - name: testcase
        image: solsson/kube-test-nodejs@sha256:1a4933cea8f7da9e5d51ec41ee5bcf8b387b3eb075f8b1e772a3821325fd3301
        workingDir: /test
        env:
        - name: TESTS
          value: "*.js"
        # Test set up
        command:
        - /bin/bash
        - -e
        - /test/setup.sh
        # Test run, again and again
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -e
            - /test/run.sh
        # Test quit on nonzero exit
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -e
            - /test/quit-on-nonzero-exit.sh
        volumeMounts:
        - name: config
          mountPath: /test
      volumes:
      - name: config
        configMap:
          name: kube-test-boilerplate
