---
kind: ConfigMap
metadata:
  name: kube-test-boilerplate
  namespace: default
apiVersion: v1
data:

  setup.sh: |-
    touch /tmp/testlog

    tail -f /tmp/testlog

  run.sh: |-
    exec >> /tmp/testlog
    exec 2>&1

    echo "No tests yet, at $(date -u --iso-8601='ns')"

    exit 0

  continue.sh: |-
    exec >> /tmp/testlog
    exec 2>&1

    exit 0

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kube-test-boilerplate
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        test-target: kube-test
        test-type: readiness
    spec:
      containers:
      - name: testcase
        image: solsson/kube-test-bash@sha256:c98d7fb5e9365eab391a5dcd4230fc6e72caf929c60f29ff091e3b0215124713
        env:
        - name: DUMMY
          value: x
        # Test set up
        command:
        - /bin/bash
        - -e
        - /test/setup.sh
        # Test run, again and again
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -e
            - /test/run.sh
        # Test quit on nonzero exit
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -e
            - /test/continue.sh
        volumeMounts:
        - name: config
          mountPath: /test
      volumes:
      - name: config
        configMap:
          name: kube-test-boilerplate
